# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpageapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webpageclasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=254)),
                ('body', models.TextField()),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Webpageclass',
        ),
    ]
